---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - conduit.mnke.org
  resources:
  - exchanges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - conduit.mnke.org
  resources:
  - exchanges/finalizers
  verbs:
  - update
- apiGroups:
  - conduit.mnke.org
  resources:
  - exchanges/status
  verbs:
  - get
  - patch
  - update
